---
name: LF Energy Ambassador Application
description: Apply to be an LF Energy Ambassador.
title: 'Ambassador Application - NAME'
labels: ["4-ambassador-application"]
assignees:
  - lfenergy
body:
  - type: markdown
    attributes:
      value: |
        Thank you for your interested in the LF Energy Foundation Ambassador Program. Please put your name in the title above replacing NAME, and then answer the questions below to be considered for the program. Please refer to the guideance in the [Ambassador Program Overview](https://lfenergy.org/ambassador-program/) if you have any questions.
  - type: input
    attributes:
      label: Email
    validations:
      required: true
  - type: input
    attributes:
      label: Job title and organization name
      description:
    validations:
      required: true
  - type: textarea
    attributes:
      label: Bio
      description: Tell us about your background
    validations:
      required: true
  - type: dropdown
    attributes:
      label: LF Energy projects you would like to be an Ambassador for
      multiple: true
      options:
        - EVerest
        - Grid eXchange Fabric
        - OperatorFabric
        - PowSyBl
        - SEAPATH
        - SOGNO
        - CoMPAS
        - DynaÏ‰o
        - FledgePOWER
        - FlexMeasures
        - Grid Capacity Map
        - Hyphae
        - OpenEEmeter
        - openLEADR
        - OpenSTEF
        - Shapeshifter
        - Arras
        - OpenGEH
        - Power Grid Model
        - Real Time Data Ingestion Platform (RTDIP)
    validations:
      required: true 
  - type: textarea
    attributes:
      label: List any other topics you would be able to speak about
    validations:
      required: true
  - type: textarea
    attributes:
      label: Why do you want to be an Ambassador?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Please attach a headshot
    validations:
      required: true
